thomasmny/BuildSystem

plugin/src/main/java/de/eintosti/buildsystem/BuildSystem.java
plugin/src/main/java/de/eintosti/buildsystem/command/WorldsCommand.java
plugin/src/main/java/de/eintosti/buildsystem/inventory/SettingsInventory.java
plugin/src/main/java/de/eintosti/buildsystem/listener/PlayerChangedWorldListener.java
plugin/src/main/java/de/eintosti/buildsystem/listener/PlayerInteractListener.java
plugin/src/main/java/de/eintosti/buildsystem/listener/PlayerJoinListener.java
plugin/src/main/java/de/eintosti/buildsystem/listener/PlayerMoveListener.java
plugin/src/main/resources/config.yml

I have built in the possibility to change the item of the navigator.

Added custom navigator item option

---

plugin/src/main/java/de/eintosti/buildsystem/util/Messages.java

removed double entry for enter permission and replaced it with enter project.

Fix - Update Messages.java

---

plugin/src/main/java/de/eintosti/buildsystem/command/WorldsCommand.java
plugin/src/main/java/de/eintosti/buildsystem/inventory/CreateInventory.java
plugin/src/main/java/de/eintosti/buildsystem/listener/InventoryClickListener.java
plugin/src/main/java/de/eintosti/buildsystem/manager/InventoryManager.java
plugin/src/main/java/de/eintosti/buildsystem/manager/WorldManager.java
plugin/src/main/java/de/eintosti/buildsystem/object/world/World.java
plugin/src/main/java/de/eintosti/buildsystem/object/world/WorldType.java
plugin/src/main/java/de/eintosti/buildsystem/util/Messages.java
plugin/src/main/java/de/eintosti/buildsystem/util/config/WorldConfig.java

Hallo :)
Ich habe mir mal unter Issues diesen einen Beitrag #9  durchgelesen und dachte mir, dass ein CustomGenerator nicht schlecht wäre.
Jedenfalls habe ich das CreateInventory "überarbeitet"
Wenn man draufklickt wird man gefragt, wie die Welt heißen soll und danach welche Generator genutzt werden soll.
Ich habe mich, was die Selektion des Generators angeht, sehr stark vom Import inspirieren lassen 💯 
Zudem, beim Laden der Welt wurde der Generator zurück gesetzt. Das habe ich gleich mit behoben, nach 4 Stunden schlaf ^^
Heißt soviel wie: **Guck da nochmal drüber**.
Die Finale Jar funktionierte bei mir einwandfrei. (getestet* auf 1.8.8 und 1.17.1)
Zudem musste ich zum builden eine dependency rausnehmen ~ habs nicht commited ~ keine Ahnung wo bzw. was es ist.
` …

World generator update

---

.gitignore
plugin/src/main/java/de/eintosti/buildsystem/BuildSystem.java
plugin/src/main/java/de/eintosti/buildsystem/command/WorldsCommand.java
plugin/src/main/java/de/eintosti/buildsystem/object/world/World.java
plugin/src/main/java/de/eintosti/buildsystem/tabcomplete/WorldsTabComplete.java
plugin/src/main/java/de/eintosti/buildsystem/util/Messages.java

In this little update I've added a command that allows you to remove the spawn you've set.
Also I've updated the gitignore.

Remove the World Spawn

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/WorldManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/world/BuildWorld.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/SkullCache.java
gradle.properties

Don't use standard world creator when loading worlds

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/command/WorldsCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/PlayerInteractListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/PlayerInventoryClearListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/PlayerJoinListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/PlayerManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/world/BuildWorld.java
buildsystem-core/src/main/resources/plugin.yml

* Changes the permission needed to open the navigator to `buildsystem.navigator`
* Adds a permission which is needed to receive the navigator item: `buildsystem.navigator.item`
Closes #99

Navigator permission changes 

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/WorldManager.java
gradle.properties

Correctly add feature which should have been added in #103 
Signed-off-by: Thomas Meaney <thomas.meaney@icloud.com>

Hotfix: Allow multiple private worlds

---

.github/workflows/build.yml
buildsystem-core/src/main/java/com/eintosti/buildsystem/config/ConfigValues.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/world/BuildWorld.java
buildsystem-core/src/main/resources/config.yml

_Not strongly tested_
Added 2 new Config entries:
When creating a world, a default permission will be setted depending on the config value.
Current Placeholder: %world% -> worldName
-----
**Fixed a AOB-Exception** in WorldsCommand by checking args length and provide either argsName or player#getWorld.

Permission

---

buildsystem-abstraction/adapter-1_12/src/main/java/com/eintosti/buildsystem/version/v1_12_R1/CustomBlocks_1_12_R1.java
buildsystem-abstraction/adapter-1_13/src/main/java/com/eintosti/buildsystem/version/v1_13_R1/CustomBlocks_1_13_R1.java
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/util/DirectionUtils.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/BlocksInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/BlockPlaceListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/Messages.java

Add piston head block to `/blocks`

Add piston head block

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/CreateInventory.java
buildsystem-core/src/main/resources/plugin.yml

Allows server owners to restrict which world types can be created

Add permissions to each world type creation

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/command/SkullCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/config/WorldConfig.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/BlocksInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/BuilderInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/CreateInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/FilteredWorldsInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/GameRuleInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/NavigatorInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/PrivateInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/SettingsInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/SetupInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/SpeedInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/WorldsInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/ArmorStandManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/InventoryManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/WorldManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/player/BuildPlayer.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/player/CachedValues.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/player/LogoutLocation.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/world/BuildWorld.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/world/BuildWorldCreator.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/FileUtils.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/UUIDFetcher.java
gradle.properties

Separates creating a `BuildWorld` from the `WorldManager`

Refactor code to clean up world manager

---

buildSrc/src/main/kotlin/CommonConfig.kt
buildsystem-abstraction/adapter-1_12/src/main/java/com/eintosti/buildsystem/version/v1_12_R1/CustomBlocks_1_12_R1.java
buildsystem-abstraction/adapter-1_13/src/main/java/com/eintosti/buildsystem/version/v1_13_R1/CustomBlocks_1_13_R1.java
buildsystem-abstraction/adapter-1_14/src/main/java/com/eintosti/buildsystem/version/v1_14_R1/CustomBlocks_1_14_R1.java
buildsystem-abstraction/adapter-1_17/build.gradle.kts
buildsystem-abstraction/adapter-1_17/src/main/java/com/eintosti/buildsystem/version/v1_17_R1/CustomBlocks_1_17_R1.java
buildsystem-abstraction/common/build.gradle.kts
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/customblocks/CustomBlock.java
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/customblocks/CustomBlocks.java
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/util/DirectionUtils.java
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/util/MinecraftVersion.java
buildsystem-core/build.gradle.kts
buildsystem-core/src/main/java/com/eintosti/buildsystem/Messages.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/NoAICommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/inventory/BlocksInventory.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/BlockPlaceListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/EntitySpawnListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/SettingsInteractListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/manager/InventoryManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/object/internal/ServerVersion.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/EntityAIManager.java
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts

Add invisible item frame to `/blocks`

---

buildsystem-abstraction/adapter-1_12/src/main/java/com/eintosti/buildsystem/version/v1_12_R1/CustomBlocks_1_12_R1.java
buildsystem-abstraction/adapter-1_12/src/main/java/com/eintosti/buildsystem/version/v1_12_R1/GameRules_1_12_R1.java
buildsystem-abstraction/adapter-1_13/src/main/java/com/eintosti/buildsystem/version/v1_13_R1/CustomBlocks_1_13_R1.java
buildsystem-abstraction/adapter-1_13/src/main/java/com/eintosti/buildsystem/version/v1_13_R1/GameRules_1_13_R1.java
buildsystem-abstraction/adapter-1_14/src/main/java/com/eintosti/buildsystem/version/v1_14_R1/CustomBlocks_1_14_R1.java
buildsystem-abstraction/adapter-1_17/src/main/java/com/eintosti/buildsystem/version/v1_17_R1/CustomBlocks_1_17_R1.java
buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/util/DirectionUtil.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/SettingsInteractListener.java

Fixes custom blocks not being placed

Call `BlockPlaceEvent` when disable interactions are enabled

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/BuildSystem.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/BuildCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/BlockPlaceListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/BuildWorldResetUnloadListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/EditSessionListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/InventoryCreativeListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/NavigatorListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/PlayerCommandPreprocessListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/listener/PlayerQuitListener.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/player/CachedValues.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/settings/SettingsManager.java

Also disabled build mode whenever a player leaves the server

Reset player inventory when leaving build mode

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/Messages.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/BuildSystemCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/WorldsCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/HelpSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/InfoSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/InventoryUtil.java

Do not send messages if their content is empty. 
This allows subcommands to be hidden from command such as `/worlds help`
Also fixes some placeholder mistakes in`/worlds info`
Closes #165

Don't send blank messages

---

buildsystem-core/src/main/java/com/eintosti/buildsystem/Messages.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/BuildSystemCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/PagedCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/WorldsCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/SubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/AddBuilderSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/BuildersSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/DeleteSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/EditSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/HelpSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/ImportAllSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/ImportSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/InfoSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/ItemSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/RemoveBuilderSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/RemoveSpawnSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/RenameSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetCreatorSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetItemSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetPermissionSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetProjectSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetSpawnSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/SetStatusSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/TeleportSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/UnimportSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/InventoryUtil.java

- Command now has argument `/buildsystem [page]`. 
- Each page has a maximum of **7** commands. Commands without text are not sent to the player (#167)

Split `/buildsystem` into multiple pages

---

buildsystem-abstraction/common/src/main/java/com/eintosti/buildsystem/version/util/MinecraftVersion.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/Messages.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/ImportAllSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/command/subcommand/worlds/ImportSubCommand.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/settings/SettingsManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/tabcomplete/WorldsTabComplete.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/ArgumentParser.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/util/external/PlayerChatInput.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/world/BuildWorldCreator.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/world/WorldManager.java
buildsystem-core/src/main/java/com/eintosti/buildsystem/world/modification/CreateInventory.java

+ **Fix worlds being not imported correctly**
» I assume 3535dd2 introduced the bug(s)
+ Improve `/worlds import` command
» Add `-c <creator>` argument to specify which player should be the creator of the imported world

Fix worlds being not imported correctly & improvements to command

---

buildsystem-core/src/main/java/de/eintosti/buildsystem/Messages.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/color/IlleniumColorAPI.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/color/ColorPattern.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/color/IlleniumColorAPI.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/color/impl/GradientPattern.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/color/impl/RainbowPattern.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/color/impl/SolidPattern.java

Implemented other rgb color classes for gradients, rainbow effects and solid hex patterns

Changed color apis

---

buildsystem-abstraction/adapter-1_14/src/main/java/de/eintosti/buildsystem/version/v1_14_R1/CustomBlocks_1_14_R1.java
buildsystem-abstraction/adapter-1_17/src/main/java/de/eintosti/buildsystem/version/v1_17_R1/CustomBlocks_1_17_R1.java
buildsystem-abstraction/adapter-1_20/src/main/java/de/eintosti/buildsystem/version/v1_20_R1/CustomBlocks_1_20_R1.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/listener/SettingsInteractListener.java

- Add ability to place some missing plants
- Fix vines being a full block

Improvements to "Place Plants" setting

---

buildsystem-core/src/main/java/de/eintosti/buildsystem/util/ArgumentParser.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/FileUtils.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/util/StringUtils.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/world/BuildWorldCreator.java
buildsystem-core/src/main/java/de/eintosti/buildsystem/world/WorldManager.java

The structure of important classes has been revised and improved. Tests were successful in my case. However, please conduct further tests.

Improved some util classes
